/*
 * Course: CSC1020
 * Lab 2 - Exceptions
 * Main Driver class
 * Name: Matthew Bender
 * Last Updated: 9/11/2024
 */
package benderm;

import java.util.Scanner;

/**
 * Unfinished. Asks user for dice specifications and creates an array of Die objects.
 */
public class Driver {
    public static final int MIN_DICE = 2;
    public static final int MAX_DICE = 10;

    public static void main(String[] args) {
        int[] input = getInput();
        int numDice = input[0];
        int numSides = input[1];
        int numRolls = input[2];
        Die[] dice = createDice(numDice, numSides);
        int[] rolls = rollDice(dice, numSides, numRolls);
        int max = findMax(rolls);
        report(numDice, rolls, max);
    }

    /**
     * Asks user for number of dice, size of dice, and number of trials.
     *
     * @return [0:number of dice, 1:size of dice, 2:number of trials]
     */
    private static int[] getInput() {
        int[] nums = new int[3];
        Scanner sc = new Scanner(System.in);

        boolean isValid = false;
        while (!isValid) {
            isValid = true;
            System.out.println("Please enter three numbers separated by a space: " +
                    "number of dice, size of dice, and number of trials.");
            String input = sc.nextLine();

            String[] splitInput = input.split(" ");
            if (splitInput.length != 3) {
                System.out.println("Improper separation. Try again.");
                isValid = false;
            }

            try {
                for (int i = 0; i < 3; i++) {
                    nums[i] = Integer.parseInt(splitInput[i]);
                }
            } catch (NumberFormatException e) {
                System.out.println("Includes non-decimal non-space character " +
                        "or only two numbers. Try again.");
                isValid = false;
            }

            if (nums[0] < MIN_DICE) {
                System.out.println("You can't have less than " + MIN_DICE + " dice.");
                isValid = false;
            } else if (nums[0] > MAX_DICE) {
                System.out.println("You can't have more than " + MAX_DICE + " dice.");
                isValid = false;
            }

            if (nums[1] < Die.MIN_SIDES) {
                System.out.println("Dice can't have less than " + Die.MIN_SIDES + " sides.");
                isValid = false;
            } else if (nums[1] > Die.MAX_SIDES) {
                System.out.println("Dice can't have more than " + Die.MAX_SIDES + " sides.");
                isValid = false;
            }
        }

        sc.close();
        return nums;
    }

    /**
     * Instantiates an array of Die objects.
     *
     * @param numDice length of the array - number of dice
     * @param numSides size of dice - maximum number that can be generated by dice
     * @return an array of length num filled with Die objects created with the size parameter
     */
    private static Die[] createDice(int numDice, int numSides) {
        Die[] dice = new Die[numDice];
        for (int i = 0; i < numDice; i++) {
            dice[i] = new Die(numSides);
        }

        return dice;
    }

    /**
     * Rolls dice multiple times and stores the frequency of the sums into an array.
     *
     * @param dice die array of dice to be rolled.
     * @param numSides maximum number that can be rolled by a die.
     * @param numRolls number of times to roll the dice
     * @return array of the frequency of the sums of the dice
     */
    private static int[] rollDice(Die[] dice, int numSides, int numRolls) {
        int[] rolls = new int[(numSides - 1) * dice.length + 1];

        for (int i = 0; i < numRolls; i++) {
            int sum = 0;
            for (Die die : dice) {
                die.roll();
                try {
                    sum += die.getCurrentValue();
                } catch (DieNotRolledException e) {
                    System.out.println("DICE NOT ROLLED");
                }
            }
            rolls[sum - dice.length]++;
        }

        return rolls;
    }

    /**
     * Find the highest number in an array.
     *
     * @param rolls array to be searched.
     * @return the largest value found in the array.
     */
    private static int findMax(int[] rolls) {
        int max = 0;
        for (int i = 0; i < rolls.length; i++) {
            if (rolls[i] > max) {
                max = rolls[i];
            }
        }
        return max;
    }

    /**
     * Prints out a visual chart (also with numbers) of each sum and how many times it occurred.
     *
     * @param numDice number of dice that were rolled each time.
     * @param rolls frequency of each sum.
     * @param max largest value in rolls.
     */
    private static void report(int numDice, int[] rolls, int max) {
        double scale = (double) max / 10;
        int indent = ("" + (rolls.length + numDice - 1)).length();

        for (int i = 0; i < rolls.length; i++) {
            System.out.print(i + numDice);
            int numSpaces = indent - ("" + (i + numDice)).length();
            for (int j = 0; j < numSpaces; j++) {
                System.out.print(" ");
            }
            System.out.print(":" + rolls[i] + "\t");
            for (double total = rolls[i]; total >= scale; total -= scale) {
                System.out.print("*");
            }
            System.out.println();
        }
    }
}